---
- name: create & push image
  hosts: build
  become: yes
  gather_facts: false

  roles:
    - common
    - build

- name: pull image & run container
  hosts: prod
  become: yes
  gather_facts: false

  roles:
    - common
    - run




